import OAI.LinearAlgebra.CirculantHadamard.CyclotomicLocalBase
import OAI.LinearAlgebra.CirculantHadamard.CyclotomicRings
import OAI.LinearAlgebra.CirculantHadamard.LocalizationMaps

namespace OAI

universe uR uS

/-!
# The actual away coefficient localization

The prime ideal is the contraction of a maximal ideal of the actual global
root ring. Its maximality follows from integrality of the coefficient
inclusion, and the single-generator theorem identifies its localization
with the unramified cyclotomic construction.
-/

noncomputable section

namespace CirculantHadamard.CyclotomicAwayLocal

open CyclotomicRings IsLocalRing

/-- The actual prime ideal on the coefficient ring with one direction omitted. -/
abbrev awayPrime (u p : ℕ) (m : Ideal (B u)) : Ideal (awayRing u p) :=
  m.comap (awayInclusion u p).toRingHom

/-- The coefficient localization used in the prime-direction comparison. -/
abbrev AwayLocal (u p : ℕ) (m : Ideal (B u)) [m.IsPrime] :=
  Localization.AtPrime (awayPrime u p m)

instance awayLocal_algebra (u p : ℕ) (m : Ideal (B u)) [m.IsPrime] :
    Algebra (awayRing u p) (AwayLocal u p m) :=
  OreLocalization.instAlgebra (R := awayRing u p) (R₀ := awayRing u p)
    (S := (awayPrime u p m).primeCompl)

/-- Integrality follows from the genuine finite integer module structure of
the global root ring, through the coefficient inclusion. -/
theorem awayInclusion_isIntegral (u p : ℕ) :
    (awayInclusion u p).toRingHom.IsIntegral := by
  apply RingHom.IsIntegral.tower_top (algebraMap ℤ (awayRing u p))
    (awayInclusion u p).toRingHom
  rw [show (awayInclusion u p).toRingHom.comp (algebraMap ℤ (awayRing u p)) =
    algebraMap ℤ (B u) from Subsingleton.elim _ _]
  exact Algebra.IsIntegral.isIntegral

theorem awayMaximal (u p : ℕ) (m : Ideal (B u)) [m.IsMaximal] :
    (awayPrime u p m).IsMaximal :=
  maximal_comap_of_integral (awayInclusion u p).toRingHom
    (awayInclusion_isIntegral u p) m

private theorem natCast_mem_comap_of_mem {R : Type uR} {S : Type uS} [CommRing R] [CommRing S]
    (f : R →+* S) (m : Ideal S) (p : ℕ) (h : (p : S) ∈ m) :
    (p : R) ∈ m.comap f := by
  change f (p : R) ∈ m
  simpa only [map_natCast] using h

theorem prime_mem_awayPrime (u p : ℕ) (m : Ideal (B u))
    (hpm : (p : B u) ∈ m) : (p : awayRing u p) ∈ awayPrime u p m :=
  natCast_mem_comap_of_mem (awayInclusion u p).toRingHom m p hpm

instance awayLocal_charZero (u p : ℕ) (m : Ideal (B u)) [m.IsPrime] :
    CharZero (AwayLocal u p m) :=
  charZero_of_injective_algebraMap
    (IsLocalization.injective (AwayLocal u p m)
      (awayPrime u p m).primeCompl_le_nonZeroDivisors)

instance awayLocal_noetherian (u p : ℕ) (m : Ideal (B u)) [m.IsPrime] :
    IsNoetherianRing (AwayLocal u p m) :=
  IsLocalization.isNoetherianRing (awayPrime u p m).primeCompl (AwayLocal u p m)
    (IsNoetherianRing.of_finite ℤ (awayRing u p))

private theorem maximalIdeal_eq_span_of_eq (S : Subalgebra ℤ ℂ) {z : ℂ} {L p : ℕ}
    (hS : S = CyclotomicLocalBase.Order z) (hz : IsPrimitiveRoot z L)
    (hp : p.Prime) (hpL : ¬ p ∣ L) (m : Ideal S) [m.IsMaximal]
    (hpm : (p : S) ∈ m) :
    maximalIdeal (Localization.AtPrime m) = Ideal.span {(p : Localization.AtPrime m)} := by
  subst S
  exact CyclotomicLocalBase.maximalIdeal_eq_span hz hp hpL m hpm

/-- The maximal ideal of the exact contracted localization is generated by
the rational prime; no ring-property premise is assumed. -/
theorem awayLocal_maximalIdeal_eq_span (u p : ℕ) (hu : Odd u)
    (hp : p ∈ u.primeFactors) (m : Ideal (B u)) [m.IsMaximal]
    (hpm : (p : B u) ∈ m) :
    maximalIdeal (AwayLocal u p m) = Ideal.span {(p : AwayLocal u p m)} := by
  let := awayMaximal u p m
  exact maximalIdeal_eq_span_of_eq (awayRing u p) (awayRing_eq_singleton u p hu)
    (eta_isPrimitiveRoot u p hu) (Nat.prime_of_mem_primeFactors hp)
    (prime_not_dvd_awayOrder u p hu hp) (awayPrime u p m)
    (prime_mem_awayPrime u p m hpm)

theorem awayLocal_prime_ne_zero (u p : ℕ) (hp : p ∈ u.primeFactors)
    (m : Ideal (B u)) [m.IsPrime] : (p : AwayLocal u p m) ≠ 0 :=
  Nat.cast_ne_zero.mpr (Nat.prime_of_mem_primeFactors hp).ne_zero

theorem awayLocal_prime_not_isUnit (u p : ℕ) (m : Ideal (B u)) [m.IsMaximal]
    (hpm : (p : B u) ∈ m) : ¬ IsUnit (p : AwayLocal u p m) := by
  have hmem := (IsLocalization.AtPrime.to_map_mem_maximal_iff (AwayLocal u p m)
    (awayPrime u p m) (p : awayRing u p)).mpr (prime_mem_awayPrime u p m hpm)
  simpa only [map_natCast, IsLocalRing.mem_maximalIdeal, mem_nonunits_iff] using hmem

theorem awayLocal_isDiscreteValuationRing (u p : ℕ) (hu : Odd u)
    (hp : p ∈ u.primeFactors) (m : Ideal (B u)) [m.IsMaximal]
    (hpm : (p : B u) ∈ m) : IsDiscreteValuationRing (AwayLocal u p m) :=
  LocalDVR.isDiscreteValuationRing_of_maximalIdeal_eq_span
    (awayLocal_prime_ne_zero u p hp m)
    (awayLocal_maximalIdeal_eq_span u p hu hp m hpm)

end CirculantHadamard.CyclotomicAwayLocal

end

end OAI
