import OAI.LinearAlgebra.CirculantHadamard.LocalDVR
import Mathlib.Basic.Complex.Basic
import Mathlib.Algebra.CharP.Algebra
import Mathlib.Algebra.Module.End
import Mathlib.RingTheory.RootsOfUnity.Minpoly
import Mathlib.RingTheory.Coprime.Lemmas
import Mathlib.RingTheory.Localization.Submodule
import Mathlib.RingTheory.Unramified.LocalRing
import Mathlib.RingTheory.Noetherian.Basic

namespace OAI

universe uK uR uA

/-!
# The unramified cyclotomic coefficient ring

We use the actual subring `ℤ[eta]` of `ℂ`. At a maximal ideal above a
rational prime not dividing the order of `eta`, its localization has maximal
ideal generated by that prime. The central argument proves the vanishing of
the universal derivation by differentiating `eta ^ L = 1`.
-/

noncomputable section

namespace CirculantHadamard.CyclotomicLocalBase

open IsLocalRing

/-- The cyclotomic order as an actual subalgebra of the complex numbers. -/
abbrev Order (eta : ℂ) := Algebra.adjoin ℤ ({eta} : Set ℂ)

/-- The distinguished root in its integral order. -/
def generator (eta : ℂ) : Order eta :=
  ⟨eta, Algebra.subset_adjoin (Set.mem_singleton eta)⟩

/-- Localization of the actual cyclotomic order at the chosen prime ideal. -/
abbrev Local (eta : ℂ) (m : Ideal (Order eta)) [m.IsPrime] :=
  Localization.AtPrime m

variable {eta : ℂ} {L p : ℕ}

theorem order_pos (hpL : ¬ p ∣ L) : 0 < L := by
  apply Nat.pos_of_ne_zero
  intro h
  apply hpL
  rw [h]
  exact dvd_zero p

/-- The genuine finite integral power basis of `ℤ[eta]`. -/
def powerBasis (hη : IsPrimitiveRoot eta L) (hL : 0 < L) :
    PowerBasis ℤ (Order eta) :=
  Algebra.adjoin.powerBasis' (hη.isIntegral hL)

@[simp] theorem powerBasis_gen (hη : IsPrimitiveRoot eta L) (hL : 0 < L) :
    (powerBasis hη hL).gen = generator eta := by
  simp [powerBasis, generator]

theorem order_finite (hη : IsPrimitiveRoot eta L) (hL : 0 < L) :
    Module.Finite ℤ (Order eta) := (powerBasis hη hL).finite

theorem order_free (hη : IsPrimitiveRoot eta L) (hL : 0 < L) :
    Module.Free ℤ (Order eta) := Module.Free.of_basis (powerBasis hη hL).basis

theorem order_noetherian (hη : IsPrimitiveRoot eta L) (hL : 0 < L) :
    IsNoetherianRing (Order eta) := by
  let := order_finite hη hL
  exact IsNoetherianRing.of_finite ℤ (Order eta)

theorem generator_pow (hη : IsPrimitiveRoot eta L) :
    generator eta ^ L = 1 := by
  apply Subtype.ext
  exact hη.pow_eq_one

theorem local_noetherian (hη : IsPrimitiveRoot eta L) (hL : 0 < L)
    (m : Ideal (Order eta)) [m.IsPrime] : IsNoetherianRing (Local eta m) :=
  IsLocalization.isNoetherianRing m.primeCompl (Local eta m) (order_noetherian hη hL)

instance local_charZero (m : Ideal (Order eta)) [m.IsPrime] : CharZero (Local eta m) :=
  charZero_of_injective_algebraMap
    (IsLocalization.injective (Local eta m) m.primeCompl_le_nonZeroDivisors)

theorem prime_ne_zero (hp : p.Prime) (m : Ideal (Order eta)) [m.IsPrime] :
    (p : Local eta m) ≠ 0 := Nat.cast_ne_zero.mpr hp.ne_zero

theorem order_not_mem (hp : p.Prime) (hpL : ¬ p ∣ L)
    (m : Ideal (Order eta)) [hm : m.IsMaximal] (hpm : (p : Order eta) ∈ m) :
    (L : Order eta) ∉ m := by
  intro hLm
  obtain ⟨a, b, hab⟩ := (hp.coprime_iff_not_dvd.mpr hpL).cast (R := Order eta)
  have hone : (1 : Order eta) ∈ m := by
    rw [← hab]
    exact m.add_mem (m.mul_mem_left a hpm) (m.mul_mem_left b hLm)
  exact hm.ne_top (m.eq_top_iff_one.mpr hone)

theorem order_isUnit (hp : p.Prime) (hpL : ¬ p ∣ L)
    (m : Ideal (Order eta)) [m.IsMaximal] (hpm : (p : Order eta) ∈ m) :
    IsUnit (L : Local eta m) := by
  simpa only [map_natCast] using
    (IsLocalization.AtPrime.isUnit_to_map_iff (Local eta m) m (L : Order eta)).mpr
      (order_not_mem hp hpL m hpm)

private theorem formallyUnramified_of_powerBasis
    {K : Type uK} {R : Type uR} {A : Type uA} [CommRing K] [CommRing R] [CommRing A] [Algebra K R] [Algebra K A]
    [Algebra R A] [IsScalarTower K R A] (M : Submonoid R) [IsLocalization M A]
    (pb : PowerBasis K R) {L : ℕ} (hL : 0 < L) (hroot : pb.gen ^ L = 1)
    (hLu : IsUnit (L : A)) : Algebra.FormallyUnramified K A := by
  let z : A := algebraMap R A pb.gen
  let D : Derivation K A (KaehlerDifferential K A) := KaehlerDifferential.D K A
  have hzpow : z ^ L = 1 := by
    dsimp [z]
    rw [← map_pow, hroot, map_one]
  have hzunit : IsUnit z := by
    apply IsUnit.of_mul_eq_one (z ^ (L - 1))
    rw [← pow_succ', Nat.sub_add_cancel hL, hzpow]
  have hDroot : D z = 0 := by
    have hpow := congrArg D hzpow
    have hzero : (L : A) • (z ^ (L - 1) • D z : KaehlerDifferential K A) =
        (0 : KaehlerDifferential K A) := by
      simpa only [Derivation.leibniz_pow, Derivation.map_one_eq_zero,
        Nat.cast_smul_eq_nsmul A] using hpow
    have hcancel : z ^ (L - 1) • D z = (0 : KaehlerDifferential K A) :=
      hLu.smul_eq_zero.mp hzero
    exact (hzunit.pow (L - 1)).smul_eq_zero.mp hcancel
  have hDorder (a : R) : D (algebraMap R A a) = 0 := by
    obtain ⟨f, hf⟩ := pb.exists_eq_aeval' a
    rw [hf]
    change D ((IsScalarTower.toAlgHom K R A) (Polynomial.aeval pb.gen f)) = 0
    rw [← Polynomial.aeval_algHom_apply, Derivation.map_aeval]
    change Polynomial.aeval z (Polynomial.derivative f) • D z = 0
    rw [hDroot, smul_zero]
  have hD (x : A) : D x = 0 := by
    obtain ⟨⟨a, s⟩, hxs⟩ := IsLocalization.surj M x
    have hd := congrArg D hxs
    rw [Derivation.leibniz, hDorder, hDorder, smul_zero, zero_add] at hd
    exact (IsLocalization.map_units A s).smul_eq_zero.mp hd
  have hspan : Submodule.span A (Set.range D) = ⊥ := by
    apply Submodule.span_eq_bot.mpr
    rintro x ⟨y, rfl⟩
    exact hD y
  have htop : (⊤ : Submodule A (KaehlerDifferential K A)) = ⊥ :=
    (KaehlerDifferential.span_range_derivation K A).symm.trans hspan
  have hall (x : KaehlerDifferential K A) : x = 0 := by
    have hx : x ∈ (⊤ : Submodule A (KaehlerDifferential K A)) := trivial
    rw [htop, Submodule.mem_bot] at hx
    exact hx
  exact ⟨⟨fun x y => (hall x).trans (hall y).symm⟩⟩

/-- Every absolute differential vanishes: the root has invertible derivative,
and the same vanishing extends across the localization denominators. -/
theorem formallyUnramified (hη : IsPrimitiveRoot eta L) (hp : p.Prime)
    (hpL : ¬ p ∣ L) (m : Ideal (Order eta)) [m.IsMaximal]
    (hpm : (p : Order eta) ∈ m) : Algebra.FormallyUnramified ℤ (Local eta m) := by
  let : Algebra (Order eta) (Local eta m) :=
    OreLocalization.instAlgebra (R := Order eta) (S := m.primeCompl) (R₀ := Order eta)
  let : SMul (Order eta) (Local eta m) :=
    (inferInstance : Algebra (Order eta) (Local eta m)).toSMul
  let : Module (Order eta) (Local eta m) := Algebra.toModule
  let : IsScalarTower ℤ (Order eta) (Local eta m) :=
    AddCommGroup.intIsScalarTower
  apply formallyUnramified_of_powerBasis m.primeCompl
    (powerBasis hη (order_pos hpL)) (order_pos hpL)
  · simpa only [powerBasis_gen] using generator_pow hη
  · exact order_isUnit hp hpL m hpm

/-- The rational prime ideal lies under the chosen maximal ideal. -/
theorem liesOver_prime (hp : p.Prime) (m : Ideal (Order eta)) [hm : m.IsMaximal]
    (hpm : (p : Order eta) ∈ m) : m.LiesOver (Ideal.span {(p : ℤ)}) := by
  have hpz : Prime (p : ℤ) := Nat.prime_iff_prime_int.mp hp
  have hmax : (Ideal.span {(p : ℤ)}).IsMaximal :=
    PrincipalIdealRing.isMaximal_of_irreducible hpz.irreducible
  constructor
  apply hmax.eq_of_le
  · apply (Ideal.ne_top_iff_one _).mpr
    change algebraMap ℤ (Order eta) 1 ∉ m
    simpa only [map_one] using (m.ne_top_iff_one.mp hm.ne_top)
  · apply Ideal.span_le.mpr
    intro x hx
    rcases Set.mem_singleton_iff.mp hx with rfl
    change algebraMap ℤ (Order eta) (p : ℤ) ∈ m
    simpa only [Ideal.mem_under, map_natCast, map_intCast, Int.cast_natCast] using hpm

/-- The maximal ideal is generated by the actual rational prime. -/
theorem maximalIdeal_eq_span (hη : IsPrimitiveRoot eta L) (hp : p.Prime)
    (hpL : ¬ p ∣ L) (m : Ideal (Order eta)) [m.IsMaximal]
    (hpm : (p : Order eta) ∈ m) :
    maximalIdeal (Local eta m) = Ideal.span {(p : Local eta m)} := by
  let := order_finite hη (order_pos hpL)
  let P : Ideal ℤ := Ideal.span {(p : ℤ)}
  let : P.IsPrime := (Ideal.span_singleton_prime (Int.natCast_ne_zero.mpr hp.ne_zero)).mpr
    (Nat.prime_iff_prime_int.mp hp)
  let : m.LiesOver P := liesOver_prime hp m hpm
  let := Localization.AtPrime.algebraOfLiesOver P m
  have hU : Algebra.IsUnramifiedAt ℤ m := formallyUnramified hη hp hpL m hpm
  have hmap := ((Algebra.isUnramifiedAt_iff_map_eq ℤ P m).mp hU).2
  simpa only [P, Ideal.map_span, Set.image_singleton, map_natCast, map_intCast,
    Int.cast_natCast] using
    hmap.symm

theorem prime_not_isUnit (m : Ideal (Order eta)) [m.IsMaximal]
    (hpm : (p : Order eta) ∈ m) : ¬ IsUnit (p : Local eta m) := by
  have hmem := (IsLocalization.AtPrime.to_map_mem_maximal_iff (Local eta m) m
    (p : Order eta)).mpr hpm
  simpa only [map_natCast, IsLocalRing.mem_maximalIdeal, mem_nonunits_iff] using hmem

/-- The concrete unramified localization is a discrete valuation ring. -/
theorem isDiscreteValuationRing (hη : IsPrimitiveRoot eta L) (hp : p.Prime)
    (hpL : ¬ p ∣ L) (m : Ideal (Order eta)) [m.IsMaximal]
    (hpm : (p : Order eta) ∈ m) : IsDiscreteValuationRing (Local eta m) := by
  let := local_noetherian hη (order_pos hpL) m
  exact LocalDVR.isDiscreteValuationRing_of_maximalIdeal_eq_span
    (prime_ne_zero hp m) (maximalIdeal_eq_span hη hp hpL m hpm)

end CirculantHadamard.CyclotomicLocalBase

end

end OAI
