import Mathlib.RingTheory.RootsOfUnity.Complex
import Mathlib.RingTheory.Adjoin.Basic
import Mathlib.RingTheory.IntegralClosure.IsIntegral.Basic
import Mathlib.Data.Nat.PrimeFin
import Mathlib.Data.Nat.GCD.BigOperators
import Mathlib.Tactic.IntervalCases
import Mathlib.Tactic.NormNum

namespace OAI

/-!
# The concrete coefficient rings for the prime comparisons

The chosen roots and all coefficient rings live in `ℂ`. The away ring is
proved to be generated by one actual primitive root of order prime to the
omitted prime. No equality of root-generated rings is an input hypothesis.
-/

noncomputable section

namespace CirculantHadamard.CyclotomicRings

open scoped BigOperators

/-- The fixed primitive root used in the `p`-direction. -/
def rho (p : ℕ) : ℂ := Complex.exp (2 * Real.pi * Complex.I / p)

theorem rho_isPrimitiveRoot (p : ℕ) (hp : p ≠ 0) : IsPrimitiveRoot (rho p) p :=
  Complex.isPrimitiveRoot_exp p hp

@[simp] theorem rho_zero : rho 0 = 1 := by simp [rho]

theorem rho_pow (p : ℕ) (hp : p ≠ 0) : rho p ^ p = 1 :=
  (rho_isPrimitiveRoot p hp).pow_eq_one

theorem I_isPrimitiveRoot : IsPrimitiveRoot Complex.I 4 := by
  apply IsPrimitiveRoot.mk_of_lt _ (by norm_num) Complex.I_pow_four
  intro j hj0 hj4
  interval_cases j <;>
    norm_num [pow_one, Complex.I_sq, Complex.I_pow_three, Complex.ext_iff]

/-- Conjugation of a complex root is an explicit nonnegative power. -/
theorem star_eq_pow_pred_of_pow_eq_one {z : ℂ} {n : ℕ}
    (hn : n ≠ 0) (hz : z ^ n = 1) : star z = z ^ (n - 1) := by
  have hz0 : z ≠ 0 := by
    intro h
    simp [h, hn] at hz
  have hnorm : ‖z‖ = 1 := Complex.norm_eq_one_of_pow_eq_one hz hn
  have hs : star z * z = 1 := by
    change (starRingEnd ℂ) z * z = 1
    rw [Complex.conj_mul', hnorm]
    norm_num
  have hp : z ^ (n - 1) * z = 1 := by
    rw [← pow_succ, Nat.sub_add_cancel (Nat.one_le_iff_ne_zero.mpr hn), hz]
  exact mul_right_cancel₀ hz0 (hs.trans hp.symm)

theorem star_rho (p : ℕ) (hp : p ≠ 0) : star (rho p) = rho p ^ (p - 1) :=
  star_eq_pow_pred_of_pow_eq_one hp (rho_pow p hp)

theorem rho_mul_star (p : ℕ) : rho p * star (rho p) = 1 := by
  by_cases hp : p = 0
  · simp [hp]
  · rw [star_rho p hp, ← pow_succ', Nat.sub_add_cancel (Nat.one_le_iff_ne_zero.mpr hp)]
    exact rho_pow p hp

def GaussianRing : Subalgebra ℤ ℂ := Algebra.adjoin ℤ ({Complex.I} : Set ℂ)

def gaussianI : GaussianRing := ⟨Complex.I, Algebra.subset_adjoin (by simp)⟩

@[simp] theorem coe_gaussianI : (gaussianI : ℂ) = Complex.I := rfl

theorem gaussianI_sq : gaussianI ^ 2 = -1 :=
  Subtype.ext Complex.I_sq

/-- A finite list of prime directions, keeping `i` in the coefficient ring. -/
def rootRing (s : Finset ℕ) : Subalgebra ℤ ℂ :=
  Algebra.adjoin ℤ (({Complex.I} : Set ℂ) ∪ rho '' (s : Set ℕ))

/-- The literal global ring in the alternating products. -/
abbrev B (u : ℕ) : Subalgebra ℤ ℂ := rootRing u.primeFactors

/-- The literal coefficient ring with the `p`-direction omitted. -/
abbrev awayRing (u p : ℕ) : Subalgebra ℤ ℂ := rootRing (u.primeFactors.erase p)

theorem I_mem_rootRing (s : Finset ℕ) : Complex.I ∈ rootRing s :=
  Algebra.subset_adjoin (Or.inl (by simp))

theorem rho_mem_rootRing (s : Finset ℕ) (p : ℕ) (hp : p ∈ s) : rho p ∈ rootRing s :=
  Algebra.subset_adjoin (Or.inr ⟨p, hp, rfl⟩)

theorem I_mem_B (u : ℕ) : Complex.I ∈ B u := I_mem_rootRing _

theorem rho_mem_B (u p : ℕ) (hp : p ∈ u.primeFactors) : rho p ∈ B u :=
  rho_mem_rootRing _ _ hp

theorem I_mem_awayRing (u p : ℕ) : Complex.I ∈ awayRing u p := I_mem_rootRing _

theorem rho_mem_awayRing (u p q : ℕ) (hq : q ∈ u.primeFactors) (hne : q ≠ p) :
    rho q ∈ awayRing u p :=
  rho_mem_rootRing _ _ (Finset.mem_erase.mpr ⟨hne, hq⟩)

theorem rootRing_mono {s t : Finset ℕ} (hst : s ⊆ t) : rootRing s ≤ rootRing t := by
  apply Algebra.adjoin_mono
  exact Set.union_subset_union_right _ (Set.image_mono hst)

theorem GaussianRing_le_rootRing (s : Finset ℕ) : GaussianRing ≤ rootRing s :=
  Algebra.adjoin_mono Set.subset_union_left

theorem awayRing_le_B (u p : ℕ) : awayRing u p ≤ B u :=
  rootRing_mono (Finset.erase_subset _ _)

def awayInclusion (u p : ℕ) : awayRing u p →ₐ[ℤ] B u :=
  Subalgebra.inclusion (awayRing_le_B u p)

def gaussianToB (u : ℕ) : GaussianRing →ₐ[ℤ] B u :=
  Subalgebra.inclusion (GaussianRing_le_rootRing _)

def gaussianToAway (u p : ℕ) : GaussianRing →ₐ[ℤ] awayRing u p :=
  Subalgebra.inclusion (GaussianRing_le_rootRing _)

@[simp] theorem coe_awayInclusion (u p : ℕ) (x : awayRing u p) :
    (awayInclusion u p x).val = x.val := by
  exact Subalgebra.coe_inclusion (R := ℤ) (A := ℂ)
    (S := awayRing u p) (T := B u) (awayRing_le_B u p) x

@[simp] theorem coe_gaussianToB (u : ℕ) (x : GaussianRing) :
    (gaussianToB u x).val = x.val := by
  exact Subalgebra.coe_inclusion (R := ℤ) (A := ℂ)
    (S := GaussianRing) (T := B u) (GaussianRing_le_rootRing _) x

@[simp] theorem coe_gaussianToAway (u p : ℕ) (x : GaussianRing) :
    (gaussianToAway u p x).val = x.val := by
  exact Subalgebra.coe_inclusion (R := ℤ) (A := ℂ)
    (S := GaussianRing) (T := awayRing u p) (GaussianRing_le_rootRing _) x

theorem gaussian_mem (s : Finset ℕ) (a b : ℤ) :
    (a : ℂ) + (b : ℂ) * Complex.I ∈ rootRing s :=
  (rootRing s).add_mem ((rootRing s).algebraMap_mem a)
    ((rootRing s).mul_mem ((rootRing s).algebraMap_mem b) (I_mem_rootRing s))

private theorem star_mem_adjoin {S : Set ℂ}
    (hS : ∀ z ∈ S, star z ∈ Algebra.adjoin ℤ S) {z : ℂ}
    (hz : z ∈ Algebra.adjoin ℤ S) : star z ∈ Algebra.adjoin ℤ S := by
  refine Algebra.adjoin_induction (p := fun z _ => star z ∈ Algebra.adjoin ℤ S)
    hS ?_ ?_ ?_ hz
  · intro a
    simp
  · intro x y _ _ hx hy
    simpa only [star_add] using (Algebra.adjoin ℤ S).add_mem hx hy
  · intro x y _ _ hx hy
    simpa only [star_mul] using (Algebra.adjoin ℤ S).mul_mem hy hx

theorem star_mem_GaussianRing {z : ℂ} (hz : z ∈ GaussianRing) :
    star z ∈ GaussianRing := by
  apply star_mem_adjoin (S := ({Complex.I} : Set ℂ)) ?_ hz
  rintro z (rfl : z = Complex.I)
  simp

theorem star_mem_rootRing (s : Finset ℕ) {z : ℂ} (hz : z ∈ rootRing s) :
    star z ∈ rootRing s := by
  apply star_mem_adjoin ?_ hz
  rintro z (hI | ⟨p, hp, rfl⟩)
  · rcases hI with rfl
    simpa [rootRing] using (rootRing s).neg_mem (I_mem_rootRing s)
  · by_cases hp0 : p = 0
    · simpa only [hp0, rho_zero, star_one, rootRing] using (rootRing s).one_mem
    · rw [star_rho p hp0]
      exact (rootRing s).pow_mem (rho_mem_rootRing s p hp) _

instance GaussianRingStarRing : StarRing GaussianRing where
  star x := ⟨star (x : ℂ), star_mem_GaussianRing x.property⟩
  star_involutive x := Subtype.ext (star_star (x : ℂ))
  star_mul x y := Subtype.ext (star_mul (x : ℂ) (y : ℂ))
  star_add x y := Subtype.ext (star_add (x : ℂ) (y : ℂ))

instance rootRingStarRing (s : Finset ℕ) : StarRing (rootRing s) where
  star x := ⟨star (x : ℂ), star_mem_rootRing s x.property⟩
  star_involutive x := Subtype.ext (star_star (x : ℂ))
  star_mul x y := Subtype.ext (star_mul (x : ℂ) (y : ℂ))
  star_add x y := Subtype.ext (star_add (x : ℂ) (y : ℂ))

@[simp] theorem coe_star_GaussianRing (x : GaussianRing) :
    ((star x : GaussianRing) : ℂ) = star (x : ℂ) := rfl

@[simp] theorem coe_star_rootRing (s : Finset ℕ) (x : rootRing s) :
    ((star x : rootRing s) : ℂ) = star (x : ℂ) := rfl

@[simp] theorem gaussianToB_star (u : ℕ) (x : GaussianRing) :
    gaussianToB u (star x) = star (gaussianToB u x) := by
  apply Subtype.ext
  exact (coe_gaussianToB u (star x)).trans
    ((coe_star_GaussianRing x).trans
      ((congrArg (star : ℂ → ℂ) (coe_gaussianToB u x).symm).trans
        (coe_star_rootRing u.primeFactors (gaussianToB u x)).symm))

@[simp] theorem gaussianToAway_star (u p : ℕ) (x : GaussianRing) :
    gaussianToAway u p (star x) = star (gaussianToAway u p x) := by
  apply Subtype.ext
  exact (coe_gaussianToAway u p (star x)).trans
    ((coe_star_GaussianRing x).trans
      ((congrArg (star : ℂ → ℂ) (coe_gaussianToAway u p x).symm).trans
        (coe_star_rootRing (u.primeFactors.erase p) (gaussianToAway u p x)).symm))

private theorem rho_finite_order (p : ℕ) : ∃ n : ℕ, n ≠ 0 ∧ rho p ^ n = 1 := by
  by_cases hp : p = 0
  · exact ⟨1, by decide, by simp [hp]⟩
  · exact ⟨p, hp, rho_pow p hp⟩

private theorem map_star_of_pow_eq_one (S : Subalgebra ℤ ℂ) [StarRing S]
    (hstar : ∀ x : S, ((star x : S) : ℂ) = star (x : ℂ))
    (σ : S →+* ℂ) (x : S) (n : ℕ) (hn : n ≠ 0) (hx : (x : ℂ) ^ n = 1) :
    σ (star x) = star (σ x) := by
  have hxS : x ^ n = 1 := Subtype.ext hx
  have hsource : star x = x ^ (n - 1) := by
    apply Subtype.ext
    simpa only [hstar, Subalgebra.coe_pow] using star_eq_pow_pred_of_pow_eq_one hn hx
  have htarget : σ x ^ n = 1 := by rw [← map_pow, hxS, map_one]
  rw [hsource, map_pow, star_eq_pow_pred_of_pow_eq_one hn htarget]

private theorem map_star_adjoin (S : Set ℂ) [StarRing (Algebra.adjoin ℤ S)]
    (hstar : ∀ x : Algebra.adjoin ℤ S, ((star x : Algebra.adjoin ℤ S) : ℂ) = star (x : ℂ))
    (hS : ∀ z ∈ S, ∃ n : ℕ, n ≠ 0 ∧ z ^ n = 1)
    (σ : Algebra.adjoin ℤ S →+* ℂ) (x : Algebra.adjoin ℤ S) :
    σ (star x) = star (σ x) := by
  rcases x with ⟨x, hx⟩
  refine Algebra.adjoin_induction
    (p := fun z hz => σ (star (⟨z, hz⟩ : Algebra.adjoin ℤ S)) =
      star (σ (⟨z, hz⟩ : Algebra.adjoin ℤ S))) ?_ ?_ ?_ ?_ hx
  · intro z hz
    obtain ⟨n, hn, hzn⟩ := hS z hz
    exact map_star_of_pow_eq_one _ hstar σ ⟨z, Algebra.subset_adjoin hz⟩ n hn hzn
  · intro a
    change σ (star (a : Algebra.adjoin ℤ S)) = star (σ (a : Algebra.adjoin ℤ S))
    simp
  · intro z w hz hw hzp hwp
    change σ (star ((⟨z, hz⟩ : Algebra.adjoin ℤ S) + ⟨w, hw⟩)) =
      star (σ ((⟨z, hz⟩ : Algebra.adjoin ℤ S) + ⟨w, hw⟩))
    simpa only [star_add, map_add] using congrArg₂ (· + ·) hzp hwp
  · intro z w hz hw hzp hwp
    change σ (star ((⟨z, hz⟩ : Algebra.adjoin ℤ S) * ⟨w, hw⟩)) =
      star (σ ((⟨z, hz⟩ : Algebra.adjoin ℤ S) * ⟨w, hw⟩))
    simpa only [star_mul, map_mul] using congrArg₂ (· * ·) hwp hzp

/-- Every complex-valued ring map respects the actual conjugation. -/
theorem map_star_rootRing (s : Finset ℕ) (σ : rootRing s →+* ℂ) (x : rootRing s) :
    σ (star x) = star (σ x) := by
  apply @map_star_adjoin (({Complex.I} : Set ℂ) ∪ rho '' (s : Set ℕ))
    (rootRingStarRing s) (coe_star_rootRing s) ?_ σ x
  rintro z (hI | ⟨p, _, rfl⟩)
  · rcases hI with rfl
    exact ⟨4, by decide, Complex.I_pow_four⟩
  · exact rho_finite_order p

theorem map_star_B (u : ℕ) (σ : B u →+* ℂ) (x : B u) :
    σ (star x) = star (σ x) := map_star_rootRing _ σ x

theorem map_star_awayRing (u p : ℕ) (σ : awayRing u p →+* ℂ) (x : awayRing u p) :
    σ (star x) = star (σ x) := map_star_rootRing _ σ x

theorem map_star_GaussianRing (σ : GaussianRing →+* ℂ) (x : GaussianRing) :
    σ (star x) = star (σ x) := by
  apply @map_star_adjoin ({Complex.I} : Set ℂ) GaussianRingStarRing
    coe_star_GaussianRing ?_ σ x
  rintro z (rfl : z = Complex.I)
  exact ⟨4, by decide, Complex.I_pow_four⟩

private theorem integral_of_finite_order {z : ℂ} (h : ∃ n : ℕ, n ≠ 0 ∧ z ^ n = 1) :
    IsIntegral ℤ z := by
  obtain ⟨n, hn, hz⟩ := h
  apply IsIntegral.of_pow (Nat.pos_of_ne_zero hn)
  rw [hz]
  exact isIntegral_one

instance rootRing_finite (s : Finset ℕ) : Module.Finite ℤ (rootRing s) := by
  apply Algebra.finite_adjoin_of_finite_of_isIntegral
    ((Set.finite_singleton Complex.I).union (s.finite_toSet.image rho))
  rintro z (hI | ⟨p, _, rfl⟩)
  · rcases hI with rfl
    exact integral_of_finite_order ⟨4, by decide, Complex.I_pow_four⟩
  · exact integral_of_finite_order (rho_finite_order p)

instance GaussianRing_finite : Module.Finite ℤ GaussianRing :=
  Algebra.finite_adjoin_simple_of_isIntegral
    (integral_of_finite_order ⟨4, by decide, Complex.I_pow_four⟩)

private theorem primitive_mul {z w : ℂ} {m n : ℕ}
    (hz : IsPrimitiveRoot z m) (hw : IsPrimitiveRoot w n) (hcop : m.Coprime n) :
    IsPrimitiveRoot (z * w) (m * n) := by
  have horder := (Commute.all z w).orderOf_mul_eq_mul_orderOf_of_coprime
    (by simpa only [← hz.eq_orderOf, ← hw.eq_orderOf] using hcop)
  rw [← hz.eq_orderOf, ← hw.eq_orderOf] at horder
  rw [← horder]
  exact IsPrimitiveRoot.orderOf _

theorem prime_roots_prod_primitive (s : Finset ℕ) (hs : ∀ p ∈ s, Nat.Prime p) :
    IsPrimitiveRoot (∏ p ∈ s, rho p) (∏ p ∈ s, p) := by
  classical
  revert hs
  induction s using Finset.induction_on with
  | empty =>
      intro _
      simp
  | @insert p s hp ih =>
      intro hs
      have hpp := hs p (Finset.mem_insert_self p s)
      have hsp : ∀ q ∈ s, Nat.Prime q := fun q hq => hs q (Finset.mem_insert_of_mem hq)
      rw [Finset.prod_insert hp, Finset.prod_insert hp]
      apply primitive_mul (rho_isPrimitiveRoot p hpp.ne_zero) (ih hsp)
      apply Nat.coprime_prod_right_iff.mpr
      intro q hq
      apply (Nat.coprime_primes hpp (hsp q hq)).mpr
      intro heq
      exact hp (heq.symm ▸ hq)

/-- The single generator of a finite prime-root ring. -/
def etaOf (s : Finset ℕ) : ℂ := Complex.I * ∏ q ∈ s, rho q

def orderOfSet (s : Finset ℕ) : ℕ := 4 * ∏ q ∈ s, q

theorem etaOf_isPrimitiveRoot (s : Finset ℕ)
    (hs : ∀ p ∈ s, Nat.Prime p) (hodd : ∀ p ∈ s, Odd p) :
    IsPrimitiveRoot (etaOf s) (orderOfSet s) := by
  apply primitive_mul I_isPrimitiveRoot (prime_roots_prod_primitive s hs)
  apply Nat.coprime_prod_right_iff.mpr
  intro p hp
  simpa using ((hodd p hp).coprime_two_left.pow_left 2)

theorem orderOfSet_pos (s : Finset ℕ) (hs : ∀ p ∈ s, Nat.Prime p) :
    0 < orderOfSet s :=
  Nat.mul_pos (by decide) (Finset.prod_pos (fun p hp => (hs p hp).pos))

theorem rootRing_eq_singleton (s : Finset ℕ)
    (hs : ∀ p ∈ s, Nat.Prime p) (hodd : ∀ p ∈ s, Odd p) :
    rootRing s = Algebra.adjoin ℤ ({etaOf s} : Set ℂ) := by
  classical
  have hη := etaOf_isPrimitiveRoot s hs hodd
  let : NeZero (orderOfSet s) := ⟨(orderOfSet_pos s hs).ne'⟩
  have hηmem : etaOf s ∈ rootRing s :=
    (rootRing s).mul_mem (I_mem_rootRing s)
      ((rootRing s).prod_mem (fun q hq => rho_mem_rootRing s q hq))
  have hpower {z : ℂ} (hz : z ^ orderOfSet s = 1) :
      z ∈ Algebra.adjoin ℤ ({etaOf s} : Set ℂ) := by
    obtain ⟨j, _, hj⟩ := hη.eq_pow_of_pow_eq_one hz
    rw [← hj]
    exact (Algebra.adjoin ℤ ({etaOf s} : Set ℂ)).pow_mem
      (Algebra.subset_adjoin (by simp)) j
  apply le_antisymm
  · apply Algebra.adjoin_le
    rintro z (hI | ⟨q, hq, rfl⟩)
    · rcases hI with rfl
      apply hpower
      exact (I_isPrimitiveRoot.pow_eq_one_iff_dvd _).mpr (dvd_mul_right 4 _)
    · apply hpower
      apply ((rho_isPrimitiveRoot q (hs q hq).ne_zero).pow_eq_one_iff_dvd _).mpr
      exact (Finset.dvd_prod_of_mem (fun q : ℕ => q) hq).trans (dvd_mul_left _ 4)
  · apply Algebra.adjoin_le
    simpa using hηmem

def eta (u p : ℕ) : ℂ := etaOf (u.primeFactors.erase p)

def awayOrder (u p : ℕ) : ℕ := orderOfSet (u.primeFactors.erase p)

theorem eta_isPrimitiveRoot (u p : ℕ) (hu : Odd u) :
    IsPrimitiveRoot (eta u p) (awayOrder u p) := by
  apply etaOf_isPrimitiveRoot
  · intro q hq
    exact Nat.prime_of_mem_primeFactors (Finset.mem_of_mem_erase hq)
  · intro q hq
    exact hu.of_dvd_nat (Nat.dvd_of_mem_primeFactors (Finset.mem_of_mem_erase hq))

theorem awayOrder_pos (u p : ℕ) : 0 < awayOrder u p :=
  orderOfSet_pos _ (fun _q hq => Nat.prime_of_mem_primeFactors (Finset.mem_of_mem_erase hq))

theorem awayRing_eq_singleton (u p : ℕ) (hu : Odd u) :
    awayRing u p = Algebra.adjoin ℤ ({eta u p} : Set ℂ) := by
  apply rootRing_eq_singleton
  · intro q hq
    exact Nat.prime_of_mem_primeFactors (Finset.mem_of_mem_erase hq)
  · intro q hq
    exact hu.of_dvd_nat (Nat.dvd_of_mem_primeFactors (Finset.mem_of_mem_erase hq))

theorem prime_not_dvd_awayOrder (u p : ℕ) (hu : Odd u) (hp : p ∈ u.primeFactors) :
    ¬p ∣ awayOrder u p := by
  have hpp := Nat.prime_of_mem_primeFactors hp
  apply hpp.coprime_iff_not_dvd.mp
  change p.Coprime (4 * ∏ q ∈ u.primeFactors.erase p, q)
  apply Nat.coprime_mul_iff_right.mpr
  constructor
  · have hodd := hu.of_dvd_nat (Nat.dvd_of_mem_primeFactors hp)
    simpa using hodd.coprime_two_right.pow_right 2
  · apply Nat.coprime_prod_right_iff.mpr
    intro q hq
    apply (Nat.coprime_primes hpp
      (Nat.prime_of_mem_primeFactors (Finset.mem_of_mem_erase hq))).mpr
    exact (Finset.ne_of_mem_erase hq).symm

theorem B_eq_adjoin_away (u p : ℕ) (hp : p ∈ u.primeFactors) :
    B u = (Algebra.adjoin (awayRing u p) ({rho p} : Set ℂ)).restrictScalars ℤ := by
  change Algebra.adjoin ℤ (({Complex.I} : Set ℂ) ∪ rho '' (u.primeFactors : Set ℕ)) =
    (Algebra.adjoin
      (Algebra.adjoin ℤ (({Complex.I} : Set ℂ) ∪ rho '' ((u.primeFactors.erase p : Finset ℕ) : Set ℕ)))
      ({rho p} : Set ℂ)).restrictScalars ℤ
  rw [← Algebra.adjoin_union_eq_adjoin_adjoin]
  congr 1
  ext z
  constructor
  · rintro (hI | ⟨q, hq, rfl⟩)
    · exact Or.inl (Or.inl hI)
    · by_cases heq : q = p
      · exact Or.inr (by simp [heq])
      · exact Or.inl (Or.inr ⟨q, Finset.mem_erase.mpr ⟨heq, hq⟩, rfl⟩)
  · rintro ((hI | ⟨q, hq, rfl⟩) | heq)
    · exact Or.inl hI
    · exact Or.inr ⟨q, Finset.mem_of_mem_erase hq, rfl⟩
    · exact Or.inr ⟨p, hp, (Set.mem_singleton_iff.mp heq).symm⟩

end CirculantHadamard.CyclotomicRings

end

end OAI
