import OAI.LinearAlgebra.CirculantHadamard.TheoremS.Main
import OAI.LinearAlgebra.CirculantHadamard.TheoremS.Sharp
import OAI.LinearAlgebra.CirculantHadamard.TheoremS.RDS
import OAI.LinearAlgebra.CirculantHadamard.RamifiedComparison.LemmaA
import OAI.LinearAlgebra.CirculantHadamard.RamifiedComparison.TheoremC
import OAI.LinearAlgebra.CirculantHadamard.RamifiedComparison.PrimePower

/-!
# Axiom audit for the public theorems

Each `#guard_msgs` block below fixes the exact `#print axioms` output of a public theorem.
The expected output lists only Lean's three standard axioms `propext`, `Classical.choice`
and `Quot.sound`. Any additional axiom (for instance the one generated by an unfinished proof, or a
user-declared `axiom`) changes the message and makes this file fail to build.
-/

namespace OAI.CirculantHadamard.PrimeOnceAudit

/-- info: 'OAI.CirculantHadamard.TheoremS.no_perfect_function' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms OAI.CirculantHadamard.TheoremS.no_perfect_function

/-- info: 'OAI.CirculantHadamard.TheoremS.no_perfect_sequence' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms OAI.CirculantHadamard.TheoremS.no_perfect_sequence

/-- info: 'OAI.CirculantHadamard.TheoremS.no_perfect_quaternary_sequence' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms OAI.CirculantHadamard.TheoremS.no_perfect_quaternary_sequence

/-- info: 'OAI.CirculantHadamard.TheoremS.no_perfect_function_sharp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms OAI.CirculantHadamard.TheoremS.no_perfect_function_sharp

/-- info: 'OAI.CirculantHadamard.TheoremS.no_perfect_sequence_sharp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms OAI.CirculantHadamard.TheoremS.no_perfect_sequence_sharp

/-- info: 'OAI.CirculantHadamard.TheoremS.no_perfect_sequence_two_mod_four' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms OAI.CirculantHadamard.TheoremS.no_perfect_sequence_two_mod_four

/-- info: 'OAI.CirculantHadamard.TheoremS.RDSCheck.no_semiregular_rds' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms OAI.CirculantHadamard.TheoremS.RDSCheck.no_semiregular_rds

/-- info: 'OAI.CirculantHadamard.RamifiedComparison.lemmaA' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms OAI.CirculantHadamard.RamifiedComparison.lemmaA

/-- info: 'OAI.CirculantHadamard.RamifiedComparison.not_exists_perfect_prime_phase' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms OAI.CirculantHadamard.RamifiedComparison.not_exists_perfect_prime_phase

/-- info: 'OAI.CirculantHadamard.RamifiedComparison.not_exists_perfect_prime_power_phase' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms OAI.CirculantHadamard.RamifiedComparison.not_exists_perfect_prime_power_phase

end OAI.CirculantHadamard.PrimeOnceAudit
