import OAI.LinearAlgebra.CirculantHadamard.RamifiedEisenstein
import OAI.LinearAlgebra.CirculantHadamard.RamifiedUnit
import OAI.LinearAlgebra.CirculantHadamard.LocalDVR
import Mathlib.RingTheory.Ideal.GoingUp
import Mathlib.RingTheory.Polynomial.Cyclotomic.Eval

namespace OAI

universe uA

/-!
# The actual ramified cyclotomic local ring

We adjoin a root of the prime-power cyclotomic polynomial to the given
characteristic-zero DVR. Every maximal ideal of this finite integral extension
is shown to be generated by the actual element `root - 1`.
-/

noncomputable section

namespace CirculantHadamard.RamifiedLocal

open Polynomial

/-- The genuine monic cyclotomic quotient, with no additional ring-data premise. -/
abbrev Extension (A : Type uA) [CommRing A] (p k : ℕ) :=
  AdjoinRoot (cyclotomic (p ^ (k + 1)) A)

/-- The actual ramified parameter in the cyclotomic quotient. -/
def uniformizer (A : Type uA) [CommRing A] (p k : ℕ) : Extension A p k :=
  AdjoinRoot.root (cyclotomic (p ^ (k + 1)) A) - 1

instance extensionFinite (A : Type uA) [CommRing A] (p k : ℕ) :
    Module.Finite A (Extension A p k) :=
  (cyclotomic.monic (p ^ (k + 1)) A).finite_adjoinRoot

theorem uniformizer_aeval_shifted (A : Type uA) [CommRing A] (p k : ℕ) :
    aeval (uniformizer A p k) (RamifiedEisenstein.shifted A p k) = 0 := by
  simp only [RamifiedEisenstein.shifted, aeval_comp, map_add, aeval_X, map_one,
    uniformizer, sub_add_cancel, AdjoinRoot.aeval_eq, AdjoinRoot.mk_self]

/-- Every element is a scalar modulo the actual root-minus-one parameter. -/
theorem exists_scalar_add_uniformizer_mul (A : Type uA) [CommRing A] (p k : ℕ)
    (x : Extension A p k) :
    ∃ a : A, ∃ b : Extension A p k,
      x = algebraMap A (Extension A p k) a + uniformizer A p k * b := by
  obtain ⟨q, rfl⟩ := AdjoinRoot.mk_surjective x
  have hroot : (q.map (algebraMap A (Extension A p k))).eval
      (AdjoinRoot.root (cyclotomic (p ^ (k + 1)) A)) =
      AdjoinRoot.mk (cyclotomic (p ^ (k + 1)) A) q := by
    rw [eval_map, ← aeval_def, AdjoinRoot.aeval_eq]
  have hone : (q.map (algebraMap A (Extension A p k))).eval 1 =
      algebraMap A (Extension A p k) (q.eval 1) := by
    rw [eval_map, eval₂_at_one]
  have hdiv := sub_dvd_eval_sub
    (AdjoinRoot.root (cyclotomic (p ^ (k + 1)) A)) (1 : Extension A p k)
    (q.map (algebraMap A (Extension A p k)))
  rw [hroot, hone] at hdiv
  obtain ⟨b, hb⟩ := hdiv
  refine ⟨q.eval 1, b, ?_⟩
  change _ = _ + (AdjoinRoot.root _ - 1) * b
  rw [← hb]
  simp

theorem prime_mem_span_uniformizer (A : Type uA) [CommRing A]
    {p : ℕ} (hp : p.Prime) (k : ℕ) :
    (p : Extension A p k) ∈ Ideal.span {uniformizer A p k} := by
  let : Fact p.Prime := ⟨hp⟩
  have hdiv := sub_dvd_eval_sub
    (AdjoinRoot.root (cyclotomic (p ^ (k + 1)) A)) (1 : Extension A p k)
    ((cyclotomic (p ^ (k + 1)) A).map (algebraMap A (Extension A p k)))
  have hdiv' : uniformizer A p k ∣ -(p : Extension A p k) := by
    simpa only [uniformizer, eval_map, AdjoinRoot.algebraMap_eq,
      AdjoinRoot.eval₂_root, eval₂_one_cyclotomic_prime_pow, zero_sub] using hdiv
  exact (Ideal.neg_mem_iff (Ideal.span {uniformizer A p k})).mp
    (Ideal.mem_span_singleton.mpr hdiv')

section LocalBase

variable (A : Type uA) [CommRing A] [IsDomain A] [CharZero A]
  [IsDiscreteValuationRing A] {p : ℕ} (hp : p.Prime) (k : ℕ)
  (hmax : IsLocalRing.maximalIdeal A = Ideal.span {(p : A)})

include hp hmax

theorem isDomain : IsDomain (Extension A p k) :=
  RamifiedEisenstein.cyclotomic_adjoinRoot_isDomain A hp k hmax

omit [CharZero A] in
/-- Every maximal ideal of the genuine quotient is the same principal ideal. -/
theorem maximal_eq_span_uniformizer [CharZero A] (M : Ideal (Extension A p k)) [M.IsMaximal] :
    M = Ideal.span {uniformizer A p k} := by
  have hcomap : M.comap (algebraMap A (Extension A p k)) = Ideal.span {(p : A)} :=
    (IsLocalRing.eq_maximalIdeal
      (Ideal.isMaximal_under_of_isIntegral_of_isMaximal (R := A) M)).trans hmax
  have hmap : (Ideal.span {(p : A)}).map (algebraMap A (Extension A p k)) ≤ M := by
    apply Ideal.map_le_iff_le_comap.mpr
    rw [hcomap]
  have hpow := Polynomial.IsWeaklyEisensteinAt.pow_natDegree_le_of_aeval_zero_of_monic_mem_map
      (RamifiedEisenstein.shifted_isWeaklyEisensteinAt A hp k)
      (uniformizer_aeval_shifted A p k) (RamifiedEisenstein.shifted_monic A p k)
      _ (le_refl _)
  have hpi : uniformizer A p k ∈ M :=
    (inferInstance : M.IsPrime).mem_of_pow_mem _ (hmap hpow)
  apply le_antisymm
  · intro x hx
    obtain ⟨a, b, hxform⟩ := exists_scalar_add_uniformizer_mul A p k x
    have haM : algebraMap A (Extension A p k) a ∈ M := by
      have hh := M.sub_mem hx (Ideal.mul_mem_right b M hpi)
      simpa [hxform] using hh
    have ha : a ∈ Ideal.span {(p : A)} := by
      rw [← hcomap]
      exact haM
    obtain ⟨c, hc⟩ := Ideal.mem_span_singleton.mp ha
    have hap : algebraMap A (Extension A p k) a ∈
        Ideal.span {uniformizer A p k} := by
      rw [hc, map_mul, map_natCast]
      exact Ideal.mul_mem_right _ _ (prime_mem_span_uniformizer A hp k)
    rw [hxform]
    exact (Ideal.span {uniformizer A p k}).add_mem hap
      (Ideal.mul_mem_right b _ (Ideal.subset_span (Set.mem_singleton _)))
  · exact (Ideal.span_singleton_le_iff_mem M).mpr hpi

theorem isLocalRing : IsLocalRing (Extension A p k) := by
  let : IsDomain (Extension A p k) := isDomain A hp k hmax
  obtain ⟨M, hM⟩ := Ideal.exists_maximal (Extension A p k)
  let : M.IsMaximal := hM
  apply IsLocalRing.of_unique_max_ideal
  refine ⟨M, hM, ?_⟩
  intro N hN
  let : N.IsMaximal := hN
  exact (maximal_eq_span_uniformizer A hp k hmax N).trans
    (maximal_eq_span_uniformizer A hp k hmax M).symm

variable [IsLocalRing (Extension A p k)]

theorem maximalIdeal_eq_span :
    IsLocalRing.maximalIdeal (Extension A p k) = Ideal.span {uniformizer A p k} :=
  maximal_eq_span_uniformizer A hp k hmax _

theorem root_residue_eq_one :
    Ideal.Quotient.mk (IsLocalRing.maximalIdeal (Extension A p k))
      (AdjoinRoot.root (cyclotomic (p ^ (k + 1)) A)) = 1 := by
  apply sub_eq_zero.mp
  rw [← map_one (Ideal.Quotient.mk (IsLocalRing.maximalIdeal (Extension A p k))),
    ← map_sub]
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  change uniformizer A p k ∈ IsLocalRing.maximalIdeal (Extension A p k)
  rw [maximalIdeal_eq_span A hp k hmax]
  exact Ideal.subset_span (Set.mem_singleton _)

theorem exists_unit_mul_uniformizer_pow :
    ∃ u : (Extension A p k)ˣ,
      (p : Extension A p k) = (u : Extension A p k) *
        uniformizer A p k ^ ((p - 1) * p ^ k) := by
  have hd : 0 < (RamifiedEisenstein.shifted A p k).natDegree := by
    rw [RamifiedEisenstein.shifted_natDegree A hp k]
    exact Nat.mul_pos (Nat.sub_pos_of_lt hp.one_lt) (pow_pos hp.pos k)
  have hcoeff : ∀ i < (RamifiedEisenstein.shifted A p k).natDegree,
      (p : A) ∣ (RamifiedEisenstein.shifted A p k).coeff i := by
    intro i hi
    exact Ideal.mem_span_singleton.mp
      ((RamifiedEisenstein.shifted_isWeaklyEisensteinAt A hp k).mem hi)
  have hpi : uniformizer A p k ∈ IsLocalRing.maximalIdeal (Extension A p k) := by
    rw [maximalIdeal_eq_span A hp k hmax]
    exact Ideal.subset_span (Set.mem_singleton _)
  obtain ⟨u, hu⟩ := RamifiedUnit.exists_unit_mul_root_pow
    (RamifiedEisenstein.shifted A p k) (p : A) (Nat.cast_ne_zero.mpr hp.ne_zero)
    (RamifiedEisenstein.shifted_monic A p k) hd
    (RamifiedEisenstein.shifted_coeff_zero A hp k) hcoeff
    (uniformizer A p k) hpi (uniformizer_aeval_shifted A p k)
  exact ⟨u, by simpa only [map_natCast, RamifiedEisenstein.shifted_natDegree A hp k] using hu⟩

omit hmax [CharZero A] [IsLocalRing (Extension A p k)] in
theorem algebraMap_injective [CharZero A] [IsLocalRing (Extension A p k)] : Function.Injective (algebraMap A (Extension A p k)) := by
  apply AdjoinRoot.of.injective_of_degree_ne_zero
  apply Polynomial.degree_ne_of_natDegree_ne
  rw [RamifiedEisenstein.cyclotomic_natDegree A hp k]
  exact Nat.ne_of_gt (Nat.mul_pos (Nat.sub_pos_of_lt hp.one_lt) (pow_pos hp.pos k))

omit hmax in
theorem charZero : CharZero (Extension A p k) where
  cast_injective m n h :=
    Nat.cast_injective (algebraMap_injective A hp k (by simpa only [map_natCast] using h))

theorem uniformizer_ne_zero : uniformizer A p k ≠ 0 := by
  intro hzero
  have hpS : (p : Extension A p k) ≠ 0 := by
    intro hpzero
    have : algebraMap A (Extension A p k) (p : A) =
        algebraMap A (Extension A p k) 0 := by simpa using hpzero
    exact (Nat.cast_ne_zero.mpr hp.ne_zero : (p : A) ≠ 0)
      (algebraMap_injective A hp k this)
  obtain ⟨u, hu⟩ := exists_unit_mul_uniformizer_pow A hp k hmax
  have hd : (p - 1) * p ^ k ≠ 0 :=
    Nat.ne_of_gt (Nat.mul_pos (Nat.sub_pos_of_lt hp.one_lt) (pow_pos hp.pos k))
  exact hpS (by simpa only [hzero, zero_pow hd, mul_zero] using hu)

variable [IsDomain (Extension A p k)]

theorem isDiscreteValuationRing : IsDiscreteValuationRing (Extension A p k) :=
  LocalDVR.isDiscreteValuationRing_of_maximalIdeal_eq_span
    (uniformizer_ne_zero A hp k hmax) (maximalIdeal_eq_span A hp k hmax)

omit [IsLocalRing (Extension A p k)] in
theorem addVal_prime [IsDiscreteValuationRing (Extension A p k)] :
    IsDiscreteValuationRing.addVal (Extension A p k) (p : Extension A p k) =
      (((p - 1) * p ^ k : ℕ) : ℕ∞) := by
  obtain ⟨u, hu⟩ := exists_unit_mul_uniformizer_pow A hp k hmax
  exact LocalDVR.addVal_eq_of_unit_mul_uniformizer_pow
    (maximalIdeal_eq_span A hp k hmax) hu

end LocalBase

end CirculantHadamard.RamifiedLocal

end

end OAI
