import Mathlib.RingTheory.DiscreteValuationRing.Basic
import Mathlib.RingTheory.Polynomial.Eisenstein.IsIntegral
import Mathlib.RingTheory.Polynomial.RationalRoot
import Mathlib.RingTheory.Polynomial.UniqueFactorization

namespace OAI

universe uA uB

/-!
# Eisenstein polynomials for the ramified cyclotomic extension

The maximal ideal is generated by the actual natural prime `p`.  We transport
the integer coefficient divisibilities and prove separately that the constant
term `p` is outside the square of the maximal ideal.  This yields irreducibility
over the local base, and hence the minimal polynomial of an actual primitive
root in any faithful domain extension.
-/

noncomputable section

namespace CirculantHadamard.RamifiedEisenstein

open Polynomial

/-- The prime-power cyclotomic polynomial translated to put the root at `ξ - 1`. -/
def shifted (A : Type uA) [CommRing A] (p k : ℕ) : A[X] :=
  (cyclotomic (p ^ (k + 1)) A).comp (X + 1)

theorem shifted_monic (A : Type uA) [CommRing A] (p k : ℕ) :
    (shifted A p k).Monic := by
  simpa only [shifted, C_1] using
    (cyclotomic.monic (p ^ (k + 1)) A).comp_X_add_C (1 : A)

theorem shifted_natDegree (A : Type uA) [CommRing A] [IsDomain A]
    {p : ℕ} (hp : p.Prime) (k : ℕ) :
    (shifted A p k).natDegree = (p - 1) * p ^ k := by
  rw [shifted, natDegree_comp, show (X + 1 : A[X]) = X + C 1 by simp,
    natDegree_X_add_C, mul_one, natDegree_cyclotomic,
    Nat.totient_prime_pow_succ hp, Nat.mul_comm]

theorem cyclotomic_natDegree (A : Type uA) [CommRing A] [Nontrivial A]
    {p : ℕ} (hp : p.Prime) (k : ℕ) :
    (cyclotomic (p ^ (k + 1)) A).natDegree = (p - 1) * p ^ k := by
  rw [natDegree_cyclotomic, Nat.totient_prime_pow_succ hp, Nat.mul_comm]

theorem shifted_coeff_zero (A : Type uA) [CommRing A]
    {p : ℕ} (hp : p.Prime) (k : ℕ) :
    (shifted A p k).coeff 0 = (p : A) := by
  rw [shifted, coeff_zero_eq_eval_zero, eval_comp,
    cyclotomic_prime_pow_eq_geom_sum hp, eval_add, eval_X, eval_one, zero_add,
    eval_finsetSum]
  simp only [eval_pow, eval_X, one_pow, Finset.sum_const, Finset.card_range,
    Nat.smul_one_eq_cast]

theorem shifted_isWeaklyEisensteinAt (A : Type uA) [CommRing A]
    {p : ℕ} (hp : p.Prime) (k : ℕ) :
    (shifted A p k).IsWeaklyEisensteinAt (Ideal.span {(p : A)}) := by
  let : Fact p.Prime := ⟨hp⟩
  have h := (cyclotomic_prime_pow_comp_X_add_one_isEisensteinAt p k).isWeaklyEisensteinAt.map
    (Int.castRingHom A)
  simpa [shifted, Ideal.submodule_span_eq, Ideal.map_span, Polynomial.map_comp] using h

section Local

variable (A : Type uA) [CommRing A] [IsDomain A] [CharZero A] [IsLocalRing A]
  {p : ℕ} (hp : p.Prime) (k : ℕ)
  (hmax : IsLocalRing.maximalIdeal A = Ideal.span {(p : A)})

include hp hmax

theorem shifted_isEisensteinAt :
    (shifted A p k).IsEisensteinAt (IsLocalRing.maximalIdeal A) := by
  have hp0 : (p : A) ≠ 0 := Nat.cast_ne_zero.mpr hp.ne_zero
  have hpu : ¬ IsUnit (p : A) :=
    (IsDiscreteValuationRing.irreducible_of_span_eq_maximalIdeal (p : A) hp0 hmax).not_isUnit
  apply (shifted_monic A p k).isEisensteinAt_of_mem_of_notMem
    (Ideal.IsPrime.ne_top inferInstance)
  · intro i hi
    rw [hmax]
    exact (shifted_isWeaklyEisensteinAt A hp k).mem hi
  · rw [shifted_coeff_zero A hp k, hmax, Ideal.span_singleton_pow,
      Ideal.mem_span_singleton]
    intro h
    have h21 : (2 : ℕ) ≤ 1 := (pow_dvd_pow_iff hp0 hpu).mp (by simpa using h)
    exact (by decide : ¬ (2 : ℕ) ≤ 1) h21

theorem shifted_irreducible : Irreducible (shifted A p k) := by
  apply (shifted_isEisensteinAt A hp k hmax).irreducible inferInstance
    (shifted_monic A p k).isPrimitive
  rw [shifted_natDegree A hp k]
  exact Nat.mul_pos (Nat.sub_pos_of_lt hp.one_lt) (pow_pos hp.pos k)

theorem cyclotomic_irreducible : Irreducible (cyclotomic (p ^ (k + 1)) A) := by
  apply (MulEquiv.irreducible_iff (Polynomial.algEquivAevalXAddC (1 : A))).mp
  change Irreducible ((cyclotomic (p ^ (k + 1)) A).comp (X + C (1 : A)))
  simpa only [shifted, C_1] using shifted_irreducible A hp k hmax

/-- Modulo the maximal ideal, the translated polynomial is exactly a pure power. -/
theorem mod_maximal_shifted :
    (shifted A p k).map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A)) =
      (X : (A ⧸ IsLocalRing.maximalIdeal A)[X]) ^ ((p - 1) * p ^ k) := by
  ext i
  rw [coeff_map, coeff_X_pow]
  by_cases hi : i = (p - 1) * p ^ k
  · subst i
    rw [ite_eq_left rfl, ← shifted_natDegree A hp k,
      (shifted_monic A p k).coeff_natDegree, map_one]
  · rw [ite_eq_right hi]
    apply Ideal.Quotient.eq_zero_iff_mem.mpr
    apply (shifted_isEisensteinAt A hp k hmax).coeff_mem
    simpa only [shifted_natDegree A hp k] using hi

end Local

section DVR

variable (A : Type uA) [CommRing A] [IsDomain A] [CharZero A]
  [IsDiscreteValuationRing A] {p : ℕ} (hp : p.Prime) (k : ℕ)
  (hmax : IsLocalRing.maximalIdeal A = Ideal.span {(p : A)})

include hp hmax

theorem cyclotomic_prime : Prime (cyclotomic (p ^ (k + 1)) A) :=
  irreducible_iff_prime.mp (cyclotomic_irreducible A hp k hmax)

theorem cyclotomic_adjoinRoot_isDomain :
    IsDomain (AdjoinRoot (cyclotomic (p ^ (k + 1)) A)) :=
  AdjoinRoot.isDomain_of_prime (cyclotomic_prime A hp k hmax)

/-- The minimal polynomial equality is for the actual primitive root in a
faithful domain extension, not merely for the formal quotient root. -/
theorem cyclotomic_eq_minpoly {B : Type uB} [CommRing B] [IsDomain B]
    [Algebra A B] [NoZeroSMulDivisors A B] {ξ : B}
    (hξ : IsPrimitiveRoot ξ (p ^ (k + 1))) :
    cyclotomic (p ^ (k + 1)) A = minpoly A ξ := by
  have hroot : aeval ξ (cyclotomic (p ^ (k + 1)) A) = 0 := by
    rw [aeval_def, eval₂_eq_eval_map, map_cyclotomic, ← IsRoot.def]
    exact hξ.isRoot_cyclotomic (pow_pos hp.pos (k + 1))
  have hi : IsIntegral A ξ := ⟨_, cyclotomic.monic _ A, hroot⟩
  have hd : minpoly A ξ ∣ cyclotomic (p ^ (k + 1)) A :=
    minpoly.isIntegrallyClosed_dvd hi hroot
  exact Polynomial.eq_of_monic_of_associated (cyclotomic.monic _ A) (minpoly.monic hi)
    ((minpoly.irreducible hi).associated_of_dvd
      (cyclotomic_irreducible A hp k hmax) hd).symm

end DVR

end CirculantHadamard.RamifiedEisenstein

end

end OAI
